version: '3.8'

services:
  # Spring Boot Backend Service
  backend:
    build: ./ppdoarbackend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/ppdo_ar_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - JWT_SECRET=a4IaFKF5NKCmCk5Ehe9uwoPrHDnnwT8GCYyX+xqtLgI=
      - UPLOAD_DIR=project-images/
    depends_on:
      - db
    volumes:
      - ./ppdoarbackend/project-images:/app/project-images

  # Angular Frontend Service
  frontend:
    build: ./for-dev # <-- IMPORTANT: Change this
    ports:
      - "4200:80"
    depends_on:
      - backend

  # MariaDB Database Service
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ppdo_ar_db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
